Here I try to use regression model to convert roman numeral to arabic counterpart

In [67]:
import pandas as pd
import numpy as np

from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

Load data and name the columns

In [106]:
df = pd.read_csv("data.csv", delim_whitespace=True, header=None, names=['roman_num'] + ['num']+['digit' + str(i) for i in range(17)])
df.head(9)

,roman_num,num,digit0,digit1,digit2,digit3,digit4,digit5,digit6,digit7,digit8,digit9,digit10,digit11,digit12,digit13,digit14,digit15,digit16
0,I,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,II,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
2,III,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1
3,IV,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,1
4,V,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5
5,VI,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,5
6,VII,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,5
7,VIII,8,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,5
8,IX,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,1

Split train, test dataset and some feature engineering

In [112]:
train, test = train_test_split(df, test_size=0.2, random_state=42)

Y_train = train.iloc[:,1]
X_train = train.drop(columns=['roman_num','num'])/1000

Y_test = test.iloc[:,0:2]
X_test = test.drop(columns=['roman_num','num'])/1000

In [108]:
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
Y_pred = svr_rbf.fit(X_train, Y_train).predict(X_test)

Concatenate test and pred sidy by side

In [116]:
df2 = pd.DataFrame(Y_pred)
df3 = pd.DataFrame(Y_test)
df3.assign(predict = pd.Series(Y_pred, index=df3.index))

           roman_num   num      predict
5344         VCCCXLV  5345  5167.003808
7444        VMMCDXLV  7445  7543.354946
1731       MDCCXXXII  1732  1707.909443
8719       VMMMDCCXX  8720  8718.757527
4521       MMMMDXXII  4522  4536.415631
7453        VMMCDLIV  7454  7547.323858
576          DLXXVII   577  2275.766737
7428       VMMCDXXIX  7429  7511.751226
5577       VDLXXVIII  5578  5553.406647
439             CDXL   440  4937.970448
2750         MMDCCLI  2751  2707.947431
5730        VDCCXXXI  5731  5702.332618
5271        VCCLXXII  5272  5063.413391
5652         VDCLIII  5653  5624.328117
3999            MMMM  4000  4043.784945
4556       MMMMDLVII  4557  4554.152205
582         DLXXXIII   583  2282.390418
6289          VMCCXC  6290  6298.073063
7050           VMMLI  7051  7051.828090
4894     MMMMDCCCXCV  4895  4897.477572
8697    VMMMDCXCVIII  8698  8723.347385
2249           MMCCL  2250  2244.772274
4639        MMMMDCXL  4640  4642.244898
7191        VMMCXCII  7192  7220.878248
5872     VDCCCLXXIII  5873  5872.128652
6330       VMCCCXXXI  6331  6318.915620
1963         MCMLXIV  1964  1968.321961
8242     VMMMCCXLIII  8243  8242.813004
6589           VMDXC  6590  6616.222207
8846   VMMMDCCCXLVII  8847  8858.582909
...              ...   ...          ...
4847  MMMMDCCCXLVIII  4848  4857.808525
2291        MMCCXCII  2292  2309.679734
2133        MMCXXXIV  2134  2177.932733
550              DLI   551  2252.301597
1740         MDCCXLI  1741  1737.159089
5288       VCCLXXXIX  5289  5078.428152
1817      MDCCCXVIII  1818  1797.121491
9215      VMMMMCCXVI  9216  9206.534780
5180         VCLXXXI  5181  4971.640685
3018          MMMXIX  3019  3091.527801
17             XVIII    18  4708.827390
1770        MDCCLXXI  1771  1747.637034
1888     MDCCCLXXXIX  1889  1864.907529
2152         MMCLIII  2153  2175.869932
1642        MDCXLIII  1643  1661.975785
7915        VMMCMXVI  7916  7904.166848
4193       MMMMCXCIV  4194  4262.048815
4747   MMMMDCCXLVIII  4748  4761.119987
4830    MMMMDCCCXXXI  4831  4830.107435
533           DXXXIV   534  2220.619569
132          CXXXIII   133  4188.122416
4864     MMMMDCCCLXV  4865  4865.296661
8457     VMMMCDLVIII  8458  8565.414705
964            CMLXV   965  5484.227122
9210       VMMMMCCXI  9211  9201.832845
9448     VMMMMCDXLIX  9449  9591.626964
8284     VMMMCCLXXXV  8285  8262.680581
7852     VMMDCCCLIII  7853  7856.575895
1095           MXCVI  1096  1061.950485
8871   VMMMDCCCLXXII  8872  8869.390005

[2000 rows x 3 columns]

Yeah, the precision is not acceptable